### ISSUE TITLE
`HybridObject` needs to receive platform arguments

### ISSUE THREAD

**Issue by hannojg** [mrousavy/nitro#199]
I was confused as the jsdoc states that the default generic parameter for `HybridObject` would be:

https://github.com/mrousavy/nitro/blob/2e2e67fbeb96efb4fb8bfa779d6ed009d42675d4/packages/react-native-nitro-modules/src/HybridObject.ts#L24-L35

However, when trying to generate a spec specifying no generic parameter:

```ts
export interface PointerHolder extends HybridObject {
```

i get this error: 

```
🔧  Loading nitro.json config...
🚀  Nitrogen runs at ~/Documents/Github/react-native-filament/package
    🔍  Nitrogen found 2 specs in ./src/specs
⏳  Parsing PointerHolder.nitro.ts...
⚠️   PointerHolder does not declare any platforms in HybridObject<T> - nothing can be generated.
    ❌  No specs found in PointerHolder.nitro.ts!
```

**Comment by mrousavy** [comment]
Ah right, there's some pre-parsing code that still validates this. We should just be able to remove that and everything will work.

I'll take a look at this soon, I think for now you're not blocked by just explicitly adding the type arguments right?

**Comment by hannojg** [comment]
No I am not blocked, all good, just wanted to report this for DX

**Comment by mrousavy** [comment]
Let's turn this into a discussion; do we even want a default-behaviour for this?

Let's say the user doesn't explicitly declare the platforms, so just `extends HybridObject`.
It will generate C++ code on both iOS and Android. 

1. Is that the best behaviour?
2. Why not Swift and Kotlin? 
3. What happens if a new platform (e.g. windows) gets added? Should it also generate for that?

**Comment by mrousavy** [comment]
I think this is expected. You need to specify the platforms.

**Comment by hannojg** [comment]
Agree but then we should remove the jsdoc comment about the defaults then I guess
