### ISSUE TITLE
merge this into upstream react-native?

### ISSUE THREAD

**Issue by aliraza-noon** [mrousavy/nitro#261]
hi Marc, 

this is amazing and ideally what I would like to see out of box from react-native, question why not raise a pr and merge these in upstream react-native ? 

I feel this will create fragmentation in the ecosystem at one point core team will look into direct interop with swift might not be very soon but I think it will come at one point and people will have to figure out how to back port their code

edit: btw I always had this question how much overhead penalty do we pay for objc message dispatch, but never really tried to benchmark or investigate , this is really good work 👏 

thanks

**Comment by mrousavy** [comment]
hey! thanks for the kind words. Lots of time went into Nitro and I'm glad people like it so much.

While I'd absolutely love for Nitro to be part of RN Core, I don't think this is realistic. RN Core has their own way of doing native modules (Turbo), which is mostly backwards compatible with a ton of older libraries. Nitro is a whole new system, so every library would have to migrate eventually. I guess having both in RN Core would be okay, but still not ideal.

Also, Nitro uses experimental technology (the Swift C++ interop), which seems to work very well for us but might still technically not be stable enough for some people.

I agree that a fragmentation of the ecosystem would be bad, but I think Nitro serves a little bit of a different purpose than Turbo and therefore could exist in parallel together with Turbo. There's a lot of differences like Swift instead of ObjC, instance/object-based instead of "modules", and also no **first-class** view support yet.

Maybe the Meta team has some more thoughts on this @philIip @cortinico @elicwhite

**Comment by cortinico** [comment]
> Maybe the Meta team has some more thoughts on this @philIip @cortinico @elicwhite

Jumping on this one.

We're really excited to see explorations like NitroModules in the community, and I believe there is much that the core of React Native can benefit from it.

We're actively discussing internally if and how to potentially integrate it. 
At the same time as @mrousavy mentioned, some of the technological constraints will make it impossible for us to just upstream Nitro as it is (the Swift C++ interop to name one).

**Comment by mrousavy** [comment]
> some of the technological constraints will make it impossible for us to just upstream Nitro as it is (the Swift C++ interop to name one).

The Swift C++ interop is purely optional btw. - this is (almost) all code-gen'd on library level. NitroModules itself does not need to ship Swift C++ interop stuff at all, it is just a C++ library. It currently has around 5 files that bridge stuff like ArrayBuffer to Swift using Swift C++ interop, but this can be made conditional because it is only needed if you actually choose to build a lib using Swift.

Then the codegen can be extended with Objective-C language support.
