### ISSUE TITLE
Multiple inheritance from classes 'NSObject' and 'HybridNitroInAppBrowserSpec_base'

### ISSUE THREAD

**Issue by patrickkabwe** [mrousavy/nitro#431]
### What's happening?

This implementation works fine with nitrogen v0.18.2 however it fails with nitrogen v0.19.0. tried removing the NSobject to no avail.

<img width="935" alt="image" src="https://github.com/user-attachments/assets/31cb8958-986f-44e5-8976-020a2f5a001c" />

### Reproduceable Code

```tsx
class HybridNitroInAppBrowser : NSObject, HybridNitroInAppBrowserSpec, SFSafariViewControllerDelegate {
    private weak var safariVC: SFSafariViewController?
    
    func open(url stringUrl: String, options: NitroInAppBrowserOptions?) throws {
        guard let url = URL(string: stringUrl) else {
            throw InAppBrowserError.invalidURL
        }
        
        DispatchQueue.main.async { [weak self] in
            self?.presentSafariViewController(with: url, options: options)
        }
    }
    private func presentSafariViewController(with url: URL, options: NitroInAppBrowserOptions?) {
        let configuration = SFSafariViewController.Configuration()
        configuration.barCollapsingEnabled = false
        configuration.entersReaderIfAvailable = false
        
        let safariVC = SFSafariViewController(url: url, configuration: configuration)
        self.safariVC = safariVC
        self.safariVC?.delegate = self
        
        guard let presentingViewController = RCTPresentedViewController() else {
            print("ERROR: Unable to find presenting view controller")
            return
        }
        
        presentingViewController.present(safariVC, animated: true)
    }
    
    func safariViewControllerDidFinish(_ controller: SFSafariViewController) {
        controller.dismiss(animated: true)
        self.safariVC = nil
        print("Safari view controller did finish")
    }
}
```

### Relevant log output

```shell
nil
```

### Device

iphone 16

### Nitro Modules Version

0.19.0

### Nitrogen Version

0.19.0

### Can you reproduce this issue in the Nitro Example app here?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [X] I am using Nitrogen (nitro-codegen)
- [X] I have read and followed the [Troubleshooting Guide](https://nitro.margelo.com/docs/troubleshooting).
- [ ] I created a reproduction PR to reproduce this issue here in the nitro repo. (See [Contributing](https://nitro.margelo.com/docs/contributing) for more information)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/nitro/issues) and found none.

**Comment by mrousavy** [comment]
> Yes, I can reproduce the same issue in the Example app here

Please create a PR modifying the code here to demonstrate that issue here in the example.

**Comment by mrousavy** [comment]
Ah I think I know what the issue is.

The problem is that you cannot inherit from multiple base classes at the same time, but in Nitro 19 I changed your `HybridNitroInAppBrowserSpec` to be a class instead of a `protocol`.

Hmm, tricky.

I think the solution would be for you to create another class (called `HybridNitroInAppBrowserDelegate` or something) which is an `NSObject` and `SFSafariViewControllerDelegate`, then add that as a class member inside of `HybridNitroInAppBrowser`.

So composition instead of inheritance.

Not really a Nitro issue per-say, but a breaking change for library authors.

**Comment by mrousavy** [comment]
so yes its gonna be more code (one more class that has `presentSafariViewController` and `safariViewControllerDidFinish`), but there's no way around it unfortunately because Swift does not support inheriting from multiple classes.

And I want to keep the `*Spec` a class, not a protocol, to have some defaults in there like the `hybridContext`.

**Comment by patrickkabwe** [comment]
Thanks @mrousavy got it to work. 🫡
