### ISSUE TITLE
Recommendation for handling multiple versions of nitro modules as a peer dependency?

### ISSUE THREAD

**Issue by jobpaardekooper** [mrousavy/nitro#452]
### What's happening?

Of course each user of a nitro modules library needs to install react-native-nitro-modules in their project since the library using it will need it as a peer dependency.

What is the recommended thing to do in the following situation:
I use 2 libraries created using nitro modules.
Library 1 uses nitro modules `0.20.x`.
Library 2 has not yet been updated and uses nitro modules `0.19.x`.
Now I would kind of need both versions of `react-native-nitro-modules` at the same time to run my project.

What is the recommended way of dealing with this?

Would it work to have [multiple versions installed](https://stackoverflow.com/a/60828558) at the same time. (Sorry that I have not tried but to me it seems like that would not work right?)

### Reproduceable Code

```tsx
-
```

### Relevant log output

```shell
-
```

### Device

-

### Nitro Modules Version

-

### Can you reproduce this issue in the Nitro Example app here?

I didn't try (⚠️ your issue might get ignored & closed if you don't try this)

### Additional information

- [ ] I am using Expo
- [X] I am using Nitrogen (nitro-codegen)
- [X] I have read and followed the [Troubleshooting Guide](https://nitro.margelo.com/docs/troubleshooting).
- [ ] I created a reproduction PR to reproduce this issue here in the nitro repo. (See [Contributing](https://nitro.margelo.com/docs/contributing) for more information)
- [X] I searched for [similar issues in this repository](https://github.com/mrousavy/nitro/issues) and found none.

**Comment by mrousavy** [comment]
Multiple different installations of Nitro would not work, but since there are no breaking changes in Nitro Modules core (react-native-nitro-modules) you can use 0.20. with packages that are built on 0.19 as well.

Pretty much the only changes in Nitro are changes in Nitrogen- and since those are on the library author's side (and shipped with the package) you should be able to build your apps with a different Nitro Modules version as well.
